### ISSUE TITLE
Prefer functional Components over class for stateless components

### ISSUE THREAD

**Issue by ghost** [doug-stewart/kartridge-demo#13]
https://github.com/doug-stewart/kartridge-demo/blob/a6052a1689af95d3607c1a6d80de6951fdfc4427/app/App.js#L10

**Comment by doug-stewart** [comment]
Fixed and pushed.

**Comment by plusgut** [comment]
I would argue the same thing, even for stateful components.

**Comment by doug-stewart** [comment]
Yeah I'm starting to get the impression that with React class components were just the old way of doing things and it's very much a "we don't do that anymore" sort of thing. And it _seems_ like with hooks I don't really need to.

**Comment by plusgut** [comment]
Yes it's only needed when you want the lifecycle hooks.
