### ISSUE TITLE
Use previous state

### ISSUE THREAD

**Issue by ghost** [doug-stewart/kartridge-demo#14]
https://github.com/doug-stewart/kartridge-demo/blob/a6052a1689af95d3607c1a6d80de6951fdfc4427/app/GamePage.js#L10

https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

**Comment by doug-stewart** [comment]
I thought using the `useState` hook basically bypassed that problem since it always references the current state?
