### ISSUE TITLE
Global State

### ISSUE THREAD

**Issue by ghost** [doug-stewart/kartridge-demo#16]
How background is stored in a parent component but set in a child component, and used in another. I'd like to see this be in some global shared state (https://material-ui.com/styles/api/#themeprovider). If you review your code and your re-renders aren't "bad" then this could be okay.
https://github.com/doug-stewart/kartridge-demo/blob/a6052a1689af95d3607c1a6d80de6951fdfc4427/app/GamePage.js#L8

**Comment by doug-stewart** [comment]
The only real improvement I'd love is that it didn't re-load the background when switching from the customization state to the preview state. Unfortunately that would require a deeper refactor than I'd like to do right now.

Also, where this a full React app I'd definitely want this in a context provider and not just as properties passed around. I just needed an example of that being done and this seemed a harmless way to do it.
