### ISSUE TITLE
Modalcontainer

### ISSUE THREAD

**Issue by plusgut** [doug-stewart/kartridge-demo#18]
Sorry about that, I accidentally closed the issue (It was late yesterday).  https://github.com/doug-stewart/kartridge-demo/issues/8

**Comment by doug-stewart** [comment]
Weird, that was taken from another example but yeah I totally get what you mean. It also seems like the rest of it was completely unnecessary... Thanks for that!

Fixed and pushed.

**Comment by plusgut** [comment]
now it looks so much more clean, good job
