### ISSUE TITLE
GamePage.js

### ISSUE THREAD

**Issue by plusgut** [doug-stewart/kartridge-demo#7]
The indentation of the ternary operator is off, your package.json suggests that you are using prettier why is it not used than?

**Comment by doug-stewart** [comment]
It seems to run _sometimes_. Same with ESLint. It seems to run _sometimes_. I'm pretty certain it's just an issue with how VSCode is setup (new laptop) and I haven't poked around yet.

**Comment by plusgut** [comment]
Linting should not just happen at your ide, but also at the buildprocess.

**Comment by doug-stewart** [comment]
Fixed and pushed.
