### ISSUE TITLE
ModalContainer.js

### ISSUE THREAD

**Issue by plusgut** [doug-stewart/kartridge-demo#8]
Creating a domnode by hand, is considered bad practise. If you want to have something outside of your Component structure, consider using a Portal in a different way.

**Comment by doug-stewart** [comment]
Ah, this was how I was shown. Do you have an example of a better practice? Also, can you explain why so I understand it better (and hopefully avoid similar mistakes in the future)?

**Comment by plusgut** [comment]
Weirdly code-block is in markdown not working for me...
https://pastebin.com/AdiDiRkz

The reason why you should not do this: the framework should do the job of handling the dom, the application developer should stay away from that as much as possible.
For example it is easy to forget that the dom element needs unmounting.

And also it is simply just overhead which is not needed and react does all the staff already for you.
