### ISSUE TITLE
Preview.js

### ISSUE THREAD

**Issue by plusgut** [doug-stewart/kartridge-demo#9]
https://github.com/doug-stewart/kartridge-demo/blob/master/app/Preview.js#L195

The second parameter of map is not an ID, but the index of the entity in that array.
It is bad practise to use an index as an identifier for key. That would only be okay if you never delete elements from that array, but only push new ones in there.

**Comment by doug-stewart** [comment]
So I came across that advice previously but I didn't get a sense of what was the proper alternative. Should I make a one-off string like `preview-pod-${id}` or is there a better way of making a unique ID in React that takes into account the entire app?

**Comment by plusgut** [comment]
On creation of the entity i would just simply increment a counter, nothing fancy.

**Comment by doug-stewart** [comment]
I committed a simple counter incrementer for the key on both the preview page and the pod page. I can see how the more appropriate approach for this is to have an actual unique key that would be held in the database (either a unique string or just it's ID) so the key is truly unique to the item.

Thanks!
